### ISSUE TITLE
Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js'

### ISSUE THREAD

**Issue by Albert-Gao** [redwoodjs/learn.redwoodjs.com#131]
Just a brand new project, everything works great, except for this little annoying issue, happens for all my tests

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/18282328/126063679-170d9f62-ee2b-4182-b5dc-d51e2ca9a04c.png">

All the test files will have this error every 2 minutes or something, and if you click to open the file, the error is gone, then after a while, happens again

I am using `"@redwoodjs/core": "0.35.1"` and vscode `1.58.2`

It is from this plugin:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/18282328/126120616-58d6d525-57bd-487e-9dd7-cfa76bc082cf.png">

The error message is:

```
  ● Test suite failed to run

    Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js'

    Require stack:
      node_modules/@redwoodjs/testing/dist/MockProviders.js
      node_modules/@redwoodjs/testing/dist/customRender.js
      node_modules/@redwoodjs/testing/dist/index.js
      web/src/components/ToDosCell/ToDosCell.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/dist/MockProviders.js:32:5)
```

What am I missing here?

**Comment by Albert-Gao** [comment]
Moved to https://github.com/redwoodjs/redwood/issues/3066
